title: Blog Â· Loji44
url: "https://loji44.github.io"
baseurl: ""

# å…¨å±€é¡¶éƒ¨å¯¼èˆªæ é…ç½®ã€‚æ ¼å¼ï¼š"åç§°=è·³è½¬é“¾æ¥"ï¼Œä¾‹å¦‚ "About=/about.html"
nav:
  - About=/about.html
  - TAGS=/tags.html
  - RSS=/feed.xml
  - ğŸ”SEARCH=/search.html
